name: Black
on: [push]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Run black
      run: |
        black --check .
